# Sample .travis.yml for R projects

language: r
r:
  - release
#  - devel

os:
  - linux
  - osx

sudo: false
cache: packages
warnings_are_errors: false
r_check_args: "--no-manual --timings"

env:
 global:
   - NOT_CRAN: true
   - _R_CHECK_FORCE_SUGGESTS_: true

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - Rscript -e 'Sys.getenv("NOT_CRAN")'

after_success:
  - Rscript -e 'covr::codecov()'
