# Sample .travis.yml for R projects

language: r

matrix:
  include:
  - r: release
    os: osx
  - r: release
    os: linux
    after_success: travis_wait Rscript -e 'covr::codecov()'
  - r: devel
    os: linux

sudo: false
cache: packages
warnings_are_errors: true
r_check_args: "--no-manual --timings"

env:
 global:
   - BIGSTATSR_CRAN: false
   - _R_CHECK_FORCE_SUGGESTS_: false

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - Rscript -e 'Sys.getenv("BIGSTATSR_CRAN")'

# https://github.com/travis-ci/travis-ci/issues/3849
script:
  - |
    R CMD build .
    travis_wait 30 R CMD check bigstatsr*tar.gz

after_failure:
  find *Rcheck -name '*.fail' -print -exec cat '{}' \;
